# Generated by Django 4.1.2 on 2022-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
