# Generated by Django 4.1.2 on 2022-10-27 18:48

from django.db import migrations


def load_initial_data(apps, schema_editor):
    """Carga los datos iniciales"""
    Fact = apps.get_model('facts', 'Fact')
    Fact.objects.bulk_create([
        Fact(fact="Hay 1424 cosas en una habitación promedio con las que Chuck Norris podría matarte. Incluyendo la habitación en sí."),
        Fact(fact="Chuck Norris es la medida del sistema internacional del dolor."),
        Fact(fact="Chuck Norris ganó un concurso sobre permanecer debajo del agua y ganó. Cabe destacar que su contrincante era pez."),
        Fact(fact="Las lágrimas de Chuck Norris curan el cáncer. Lástima que jamás haya llorado."),
        Fact(fact="Chuck Norris dona sangre a menudo. Pero rara vez es la suya."),
        Fact(fact="La gente usa pijamas de Superman. Superman usa pijamas de Chuck Norris.")
    ])


def reverse_func(apps, schema_editor):
    """Lógica par la reversa de la migración"""
    Fact = apps.get_model('facts', 'Fact')
    Fact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
